<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bibtexToHTML" nsURI="http://www.example.org/bibtexToHTML" nsPrefix="bibtexToHTML">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hat" lowerBound="1" upperBound="-1"
        eType="#//OutputVariant" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputVariant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hat" lowerBound="1" upperBound="-1"
        eType="#//Fields" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fields">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FontStyle" eType="#//FontStyle"
        defaultValueLiteral="Default"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FontType" eType="#//FontTypes"
        defaultValueLiteral="Times"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FontSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FontTypes">
    <eLiterals name="Arial"/>
    <eLiterals name="Times"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FontStyle">
    <eLiterals name="Bold"/>
    <eLiterals name="Italic"/>
    <eLiterals name="Default"/>
  </eClassifiers>
</ecore:EPackage>
