/**
 * generated by Xtext
 */
package de.tubs.bibtextohtml.bibtex.ui.contentassist;

import de.tubs.bibtextohtml.bibtex.ui.contentassist.AbstractBibTeXProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class BibTeXProposalProvider extends AbstractBibTeXProposalProvider {
}
