/*
* generated by Xtext
*/
package de.tubs.bibtextohtml.bibtex.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BibTeXAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/tubs/bibtextohtml/bibtex/parser/antlr/internal/InternalBibTeX.tokens");
	}
}
