/*
* generated by Xtext
*/
package de.tubs.bibtextohtml.bibtex.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.tubs.bibtextohtml.bibtex.services.BibTeXGrammarAccess;

public class BibTeXParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BibTeXGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.tubs.bibtextohtml.bibtex.parser.antlr.internal.InternalBibTeXParser createParser(XtextTokenStream stream) {
		return new de.tubs.bibtextohtml.bibtex.parser.antlr.internal.InternalBibTeXParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public BibTeXGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BibTeXGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
