/*
 * generated by Xtext
 */
package de.tubs.bibtextohtml.htmlgenerator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HTMLGeneratorUiModule extends de.tubs.bibtextohtml.htmlgenerator.ui.AbstractHTMLGeneratorUiModule {
	public HTMLGeneratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
