/**
 * generated by Xtext
 */
package de.tubs.bibtextohtml.bibtex.validation;

import de.tubs.bibtextohtml.bibtex.validation.AbstractBibTeXValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BibTeXValidator extends AbstractBibTeXValidator {
}
