/**
 * generated by Xtext
 */
package de.tubs.bibtextohtml.bibtex.validation;

import de.tubs.bibtextohtml.bibtex.bibTeX.BibTeXPackage;
import de.tubs.bibtextohtml.bibtex.bibTeX.UnknownField;
import de.tubs.bibtextohtml.bibtex.bibTeX.UnknownType;
import de.tubs.bibtextohtml.bibtex.validation.AbstractBibTeXValidator;
import org.eclipse.xtext.validation.Check;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BibTeXValidator extends AbstractBibTeXValidator {
  public final static String UNKNOWN_FIELD = "UnknownField";
  
  @Check
  public void checkForUnknowns(final UnknownField unknown) {
    UnknownType _type = unknown.getType();
    String _type_1 = _type.getType();
    String _plus = ("Field \"" + _type_1);
    String _plus_1 = (_plus + "\" is unknown or not implemented yet. Hence it will be ignored.");
    this.warning(_plus_1, 
      BibTeXPackage.Literals.UNKNOWN_FIELD__TYPE, 
      BibTeXValidator.UNKNOWN_FIELD);
  }
}
