/*
 * generated by Xtext
 */
package de.tubs.bibtextohtml.bibtex.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BibTeXUiModule extends de.tubs.bibtextohtml.bibtex.ui.AbstractBibTeXUiModule {
	public BibTeXUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
