/*
* generated by Xtext
*/
package de.tubs.bibtextohtml.bibtex;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BibTeXUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.tubs.bibtextohtml.bibtex.ui.internal.BibTeXActivator.getInstance().getInjector("de.tubs.bibtextohtml.bibtex.BibTeX");
	}
	
}
