/*
* generated by Xtext
*/
package de.tubs.bibtextohtml.bibtex;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BibTeXStandaloneSetup extends BibTeXStandaloneSetupGenerated{

	public static void doSetup() {
		new BibTeXStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

