/*
 * generated by Xtext
 */
package de.tubs.bibtextohtml.bibtex;

import org.eclipse.xtext.conversion.IValueConverterService;
import  de.tubs.bibtextohtml.bibtex.BibTeXTerminalConverters;
/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BibTeXRuntimeModule extends de.tubs.bibtextohtml.bibtex.AbstractBibTeXRuntimeModule {
//    @Override
//    public Class<? extends IValueConverterService> bindIValueConverterService() {
//            return BibTeXTerminalConverters.class;
//    }
}
