/*
 * generated by Xtext
 */
package de.tubs.bibtextohtml.bibtex;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BibTeXRuntimeModule extends de.tubs.bibtextohtml.bibtex.AbstractBibTeXRuntimeModule {

}
