/*
 * generated by Xtext
 */
package de.tubs.bibtextohtml.bibtex.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.tubs.bibtextohtml.bibtex.ui.internal.BibTeXActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BibTeXExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BibTeXActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BibTeXActivator.getInstance().getInjector(BibTeXActivator.DE_TUBS_BIBTEXTOHTML_BIBTEX_BIBTEX);
	}
	
}
