/*
 * generated by Xtext
 */
package de.tubs.bibtextohtml.htmlgenerator.ui.contentassist

import de.tubs.bibtextohtml.htmlgenerator.ui.contentassist.AbstractHTMLGeneratorProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HTMLGeneratorProposalProvider extends AbstractHTMLGeneratorProposalProvider {
}
