/*
 * generated by Xtext
 */
package de.tubs.bibtextohtml.htmlgenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HTMLGeneratorRuntimeModule extends de.tubs.bibtextohtml.htmlgenerator.AbstractHTMLGeneratorRuntimeModule {

}
