/*
* generated by Xtext
*/
package de.tubs.bibtextohtml.htmlgenerator;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class HTMLGeneratorStandaloneSetup extends HTMLGeneratorStandaloneSetupGenerated{

	public static void doSetup() {
		new HTMLGeneratorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

